node {
    def IMAGE = "djawed22/repo:latest"
    stage('clone'){
        git 'https://github.com/abdo224/django-jenkins.git'
        }
    def img = stage('build') {
        docker.build("IMAGE", ".")
        }
        
        
}
