pipeline {
    agent { dockerfile true }
    stages {
        stage('Test') {
            steps {
               success {
                   echo 'Success'
               }
            }
        }
    }
}