pipeline {
  agent any
  stages {
    // build the docker image
    stage('Build Image') {
      steps {
        dir('./mysite') {
          sh "docker build -t djawed22/repo:latest ."
        }

      }
    }
    // test the docker image
    stage('Test Image Building') {
      steps {
        sh "docker images "
      }
    }
    // push the docker image to docker hub
    stage('push image') {
      steps {

        withCredentials([usernamePassword(credentialsId: 'docker_hub_account', passwordVariable: 'pwd', usernameVariable: 'user')]) {
          sh "docker login -u ${env.user} -p ${env.pwd}"
          sh 'docker push djawed22/repo:latest'
        }
      }
    }
    // deploy the docker image with docker-compose 
    stage("Deploy") {
      steps {
        dir('./mysite') {
          sh "docker-compose down"
          sh "docker-compose up -d db"
          sh "sleep 20"
          sh "docker-compose up -d app"

        }
      }

    }
  }
}